# Generated by Django 4.0.1 on 2022-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default='null', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='batch',
            field=models.CharField(default='none', max_length=255, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='brand_manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca/Fabricante'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
