# Generated by Django 4.0.1 on 2022-05-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quality', '0002_notification_description_alter_notification_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
