# Generated by Django 4.0.1 on 2022-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quality', '0003_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='batch',
            field=models.CharField(blank=True, default='none', max_length=255, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chart_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº do prontuário'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo/Função'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Notificante'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do paciente'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
    ]
