# Generated by Django 4.0.4 on 2022-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(null=True, verbose_name='Descritivo')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Autor')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
                ('img', models.ImageField(null=True, upload_to='post_img/%Y/%m/%d/')),
            ],
        ),
    ]
