# Generated by Django 4.0.1 on 2022-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='post_img/%Y/%m/%d/%M/%S'),
        ),
    ]
