# Generated by Django 4.0.1 on 2022-04-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, verbose_name='Descritivo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Título'),
        ),
    ]
