# Generated by Django 4.0.4 on 2022-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Assunto')),
                ('file', models.FileField(null=True, upload_to='files/messages/%Y/%m', verbose_name='Anexo')),
                ('sector', models.CharField(max_length=255, null=True, verbose_name='Setor')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
