# Generated by Django 4.0.1 on 2022-04-26 17:45

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0016_alter_clipboard_id_alter_clipboarditem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', filer.fields.file.FilerFileField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TEST', to='filer.file')),
            ],
        ),
    ]
