# Generated by Django 4.0.1 on 2022-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
