# Generated by Django 4.0.1 on 2022-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messages',
            name='sector',
            field=models.TextField(max_length=255, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(null=True, upload_to='files/messages/%Y', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
    ]
