# Generated by Django 4.0.1 on 2022-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file_storage', '0002_alter_messages_options_messages_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
    ]
