# Generated by Django 4.0.1 on 2022-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file_storage', '0003_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sector',
            field=models.CharField(max_length=255, null=True, verbose_name='Setor'),
        ),
    ]
