# Generated by Django 4.0.1 on 2022-02-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('t_open', 'aberto'), ('t_answered', 'atendido'), ('t_closed', 'finalizado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='machine_number',
            field=models.IntegerField(),
        ),
    ]
