# Generated by Django 4.0.1 on 2022-02-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0002_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('t_open', 'aberto'), ('t_answered', 'atendido'), ('t_closed', 'finalizado')], default='t_open', max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
