# Generated by Django 4.0.1 on 2022-02-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0003_alter_ticket_status_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector'),
        ),
    ]
