# Generated by Django 4.0.1 on 2022-02-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0004_sector_ticket_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector'),
        ),
    ]
