# Generated by Django 4.0.1 on 2022-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0007_alter_ticket_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='TESTE', max_length=255),
        ),
    ]
