# Generated by Django 4.0.1 on 2022-02-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0008_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('atendido', 'Atendido'), ('finalizado', 'Finalizado')], default='aberto', max_length=100),
        ),
    ]
