# Generated by Django 4.0.1 on 2022-02-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0009_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrlAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HrlUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('access_list', models.ManyToManyField(to='app_ticket.HrlAccess')),
            ],
        ),
    ]
