# Generated by Django 4.0.1 on 2022-02-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0010_hrlaccess_hrlusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrlusers',
            name='access_list',
        ),
        migrations.DeleteModel(
            name='HrlAccess',
        ),
        migrations.DeleteModel(
            name='HrlUsers',
        ),
    ]
