# Generated by Django 4.0.1 on 2022-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0011_remove_hrlusers_access_list_delete_hrlaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Atendido', 'Atendido'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=100),
        ),
    ]
