# Generated by Django 4.0.1 on 2022-02-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0014_alter_category_options_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='destiny_sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.category'),
        ),
    ]
