# Generated by Django 4.0.1 on 2022-02-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0016_remove_category_destiny_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
