# Generated by Django 4.0.1 on 2022-02-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0018_alter_category_description_alter_sector_sector_name_and_more'),
    ]

    operations = []
