# Generated by Django 4.0.1 on 2022-02-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0019_remove_category_destiny_sector_and_more'),
    ]

    operations = []
