# Generated by Django 4.0.1 on 2022-02-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0020_remove_category_destiny_sector_alter_ticket_category'),
    ]

    operations = []
