# Generated by Django 4.0.1 on 2022-02-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0021_alter_ticket_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='destiny_sector',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.category'),
        ),
    ]
