# Generated by Django 4.0.1 on 2022-02-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0022_remove_category_destiny_sector_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
