# Generated by Django 4.0.1 on 2022-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0023_category_sector_alter_sector_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='machine_number',
            field=models.IntegerField(null=True),
        ),
    ]
