# Generated by Django 4.0.1 on 2022-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0025_alter_sector_sector_name_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='patrimony',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
