# Generated by Django 4.0.1 on 2022-03-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0028_ticket_user_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_responsible',
        ),
    ]
