# Generated by Django 4.0.1 on 2022-03-23 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ticket', '0031_alter_ticket_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response_user',
            field=models.ForeignKey(null=True, on_delete=models.SET('USUÁRIO DELETADO'), to=settings.AUTH_USER_MODEL),
        ),
    ]
