# Generated by Django 4.0.1 on 2022-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0032_alter_ticket_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
