# Generated by Django 4.0.1 on 2022-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0033_alter_ticket_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='machine_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
