# Generated by Django 4.0.1 on 2022-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0034_ticket_machine_description_ticket_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
