# Generated by Django 4.0.1 on 2022-03-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0035_ticket_phone_branch_ticket_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(max_length=4)),
                ('floor', models.IntegerField(max_length=2)),
                ('description', models.TextField(max_length=255, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector')),
            ],
        ),
    ]
