# Generated by Django 4.0.1 on 2022-03-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0036_phoneextensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneextensions',
            name='branch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phoneextensions',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
