# Generated by Django 4.0.1 on 2022-03-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0037_alter_phoneextensions_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneextensions',
            options={'verbose_name_plural': 'Ramais'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Setor responsável'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='machine_number',
            field=models.IntegerField(null=True, verbose_name='Número da máquina'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='patrimony',
            field=models.CharField(max_length=255, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_name',
            field=models.CharField(max_length=255, verbose_name='Requisitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor'),
        ),
    ]
