# Generated by Django 4.0.1 on 2022-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0038_alter_phoneextensions_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='machine_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo da máquina'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='patrimony',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_branch',
            field=models.CharField(max_length=255, null=True, verbose_name='Ramal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='response_user',
            field=models.CharField(max_length=255, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Número do quarto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='serial_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Número de Série'),
        ),
    ]
