# Generated by Django 4.0.1 on 2022-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0039_alter_ticket_machine_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(max_length=100, verbose_name='Setor'),
        ),
        migrations.DeleteModel(
            name='PhoneExtensions',
        ),
    ]
