# Generated by Django 4.0.1 on 2022-03-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0040_alter_sector_options_alter_sector_sector_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, verbose_name='Máquinas Hospitalares')),
            ],
            options={
                'verbose_name_plural': 'Máquinas Hospitalares',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='machine_description',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.machinetype', verbose_name='Tipo da máquina'),
        ),
    ]
