# Generated by Django 4.0.1 on 2022-04-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0042_rename_sector_name_machinetype_machine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Atendido', 'Atendido'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=100)),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Requisitante')),
                ('response_user', models.CharField(max_length=255, null=True, verbose_name='Responsável')),
                ('phone_branch', models.CharField(max_length=255, null=True, verbose_name='Ramal')),
                ('destination_address', models.CharField(max_length=500, null=True, verbose_name='Endereço de destino')),
                ('local_number', models.IntegerField(null=True, verbose_name='Nº da rua')),
                ('quarter_name', models.CharField(max_length=255, null=True, verbose_name='Bairro de destino')),
                ('city_name', models.CharField(max_length=255, null=True, verbose_name='Cidade de destino')),
                ('departure_date', models.DateTimeField(verbose_name='Data de saída')),
                ('departure_hour', models.CharField(max_length=100, null=True, verbose_name='Hora de partida')),
                ('destination_contact', models.CharField(max_length=255, null=True, verbose_name='Contato no destino')),
                ('contact_phone', models.CharField(max_length=255, null=True, verbose_name='Telefone do contato')),
                ('transport_type', models.CharField(max_length=255, null=True, verbose_name='Tipo de transporte')),
                ('patient_name', models.CharField(max_length=255, null=True, verbose_name='Nome do paciente')),
                ('patient_age', models.IntegerField(null=True, verbose_name='Idade do paciente')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name_plural': 'Chamados para Transporte',
            },
        ),
    ]
