# Generated by Django 4.0.1 on 2022-04-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0043_transportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='departure_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Data de saída'),
        ),
    ]
