# Generated by Django 4.0.1 on 2022-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0044_alter_transportrequest_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='category',
            field=models.CharField(max_length=255, null=True, verbose_name='Setor responsável'),
        ),
    ]
