# Generated by Django 4.0.4 on 2022-05-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(null=True, verbose_name='Ramal')),
                ('floor', models.IntegerField(null=True, verbose_name='Andar')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Descrição')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name_plural': 'Ramais',
            },
        ),
        migrations.CreateModel(
            name='FunctionsBySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(null=True, verbose_name='Ramal')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Nome da atividade')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name_plural': 'Funções setoriais',
            },
        ),
    ]
