# Generated by Django 4.0.1 on 2022-02-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrlusers',
            name='access_list',
        ),
        migrations.DeleteModel(
            name='HrlAccess',
        ),
        migrations.DeleteModel(
            name='HrlUsers',
        ),
    ]
