# Generated by Django 4.0.1 on 2022-03-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ticket', '0040_alter_sector_options_alter_sector_sector_name_and_more'),
        ('app_home', '0002_remove_hrlusers_access_list_delete_hrlaccess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(null=True, verbose_name='Ramal')),
                ('floor', models.IntegerField(null=True, verbose_name='Andar')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Descrição')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name_plural': 'Ramais',
            },
        ),
    ]
