# Generated by Django 4.0.1 on 2022-04-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0046_alter_transportrequest_description_and_more'),
        ('app_home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionsBySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_home.phoneextensions', verbose_name='Ramal')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_ticket.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name_plural': 'Funções setoriais',
            },
        ),
    ]
