# Generated by Django 4.0.1 on 2022-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_functionsbysector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionsbysector',
            name='branch',
            field=models.IntegerField(null=True, verbose_name='Ramal'),
        ),
    ]
