# Generated by Django 4.0.1 on 2022-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_alter_functionsbysector_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionsbysector',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome da atividade'),
        ),
    ]
